### ISSUE TITLE
Add linting and prettier

### ISSUE THREAD

**Issue by arifszn** [chkware/chkware.github.io#25]
Add linting and prettier support to this project so that future contributions will follow the same coding style and format.

**Comment by arifszn** [comment]
- Should it use separate CI/CD for checking lint on PR, or use `test-deploy.yml` to reduce build time? [TBD]
- Should it use pre commit hook? [TBD]

**Comment by 0hsn** [comment]
> Should it use separate CI/CD for checking lint on PR, or use test-deploy.yml to reduce build time?

My idea:
1. It should, cause that saves us build time
2. check of all the build okay, and check of all styling okay -- both are sanity check from our perspective. it's sort of dry run.

> Should it use pre commit hook?

It should, then it will lessen the hassle on maintainer part.

I think these should be broken into two different tickets, if we approach this way.
